# Generated by Django 5.0.7 on 2024-10-04 16:56

import django.db.models.deletion
import job_seekers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('work_status', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_graduation', models.IntegerField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('higher_secondary_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diploma_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bachelors_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masters_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('doctorate_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('present_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('present_take_home', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_take_home', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_yearly_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_incentive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('present_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('work_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('is_rotate_shift', models.BooleanField(default=False)),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_relocate', models.BooleanField(default=False)),
                ('professional_summary', models.TextField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('email_otp_count', models.IntegerField(default=3)),
                ('phone_otp_count', models.IntegerField(default=3)),
                ('bookmarks_count', models.IntegerField(default=3)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmarked_date', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='job_seekers.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_info', to='job_seekers.candidates')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postinfo', to='job_seekers.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('resume', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='job_seekers.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=50)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_form', to='job_seekers.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='OnbordingDocument',
            fields=[
                ('Onbording_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('tenth_mark_sheet', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('twelfth_mark_sheet', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('diploma_certificate', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('Bachelors_degree', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('masters_degree', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('doctorate_degree', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('aadhar_card', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('bank_book', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('experience', models.BinaryField(blank=True, null=True, validators=[job_seekers.models.validate_file_size, job_seekers.models.validate_file_type])),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_documents', to='job_seekers.candidates')),
            ],
        ),
    ]
