# Generated by Django 5.0.7 on 2024-10-17 14:02

import django.core.validators
import job_seekers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=job_seekers.models.upload_profile_pic, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), job_seekers.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='candidates',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_profile_resume, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size]),
        ),
    ]
