# Generated by Django 5.0.7 on 2024-11-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_domainforskill_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=200),
        ),
    ]
