# Generated by Django 5.0.7 on 2024-11-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0005_alter_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('edu_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LevelForEdu',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CourseForEdu',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='job_seekers.levelforedu')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationForEdu',
            fields=[
                ('specification_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='job_seekers.courseforedu')),
            ],
        ),
    ]
